services:
  backend:
    build: ./backend
    container_name: quickapi-backend
    volumes:
      - ./backend:/src
    env_file:
      - .env.backend
    ports:
      - 8000:8000
    command: >
      uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres
    networks:
      - qapi-network

  postgres:
    container_name: quickapi-postgres
    image: postgres:15
    ports:
      - 5432:5432
    env_file:
      - .env.postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - qapi-network

networks:
  qapi-network:
    driver: bridge

volumes:
  pgdata:

